### ISSUE TITLE
 May I ask how much GPU graphics MEMORY is required for the operation of this program?

### ISSUE THREAD

**Issue by fukeryester** [haha-lisa/MGAD-multimodal-guided-artwork-diffusion#2]
Hello, I'm sorry to bother you. May I ask how much GPU graphics memory is required for the operation of this program? I encountered the following error while using my GTX 3060 graphics card with 6G graphics memory: RuntimeError:CUDA out of memory. Tried to allocate 1.12 GiB(GPU 0: 6.00 GiB total capacity; 10.48 GiB already allocated. 0 bytes free; 11.05 GIB reserved in total by PyTorch). Should I switch to a server with huge graphics memory to run this code?
![Uploading 66b5ff67c8ed55e62f536f64d8a6540.png…]()

**Comment by haha-lisa** [comment]
I deployed that experiment on A40 and it took about 30+GB
